# BLE
CONFIG_BT=y
CONFIG_BT_PERIPHERAL=y
CONFIG_BT_DEVICE_NAME="IMU_XIAO"
CONFIG_BT_GATT_DYNAMIC_DB=y
CONFIG_BT_ATT_PREPARE_COUNT=2
CONFIG_BT_BAS=n

# I2C
CONFIG_I2C=y

# GPIO
CONFIG_GPIO=y

# ADC (battery)
CONFIG_ADC=y

# Logging
CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=3

# System
CONFIG_HEAP_MEM_POOL_SIZE=4096
CONFIG_MAIN_STACK_SIZE=2048

# Thread stack sizes
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=2048
